### ISSUE TITLE
audio samples?

### ISSUE THREAD

**Issue by G-Wang** [kaituoxu/Tacotron2#1]
Hi, do you have any audio samples to share for the best model you've trained? if so how many steps was the model trained for?

**Comment by kaituoxu** [comment]
Hi, I just implemented tacotron2 two days ago. The debug and training are ongoing. In egs/ljspeech/figure, there is an audio sample on 37k iterations, the attention figure looks well but the audio is not very good...
Thx :)

**Comment by G-Wang** [comment]
The attention looks very good, I'll give it a spin! Thanks for the great repo.
